# Generated by Django 2.2.5 on 2020-01-07 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='post_Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 7, 14, 40, 28, 599574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 7, 14, 40, 28, 645310, tzinfo=utc)),
        ),
    ]
