# Generated by Django 2.2.5 on 2020-01-08 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0002_auto_20200107_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='post_Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 8, 13, 40, 17, 535992, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 8, 13, 40, 17, 788051, tzinfo=utc)),
        ),
    ]
