# Generated by Django 2.2.5 on 2020-01-11 00:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0003_auto_20200108_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Blogging.blogs'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='owner_email',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 0, 23, 28, 18390, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_title',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 0, 23, 28, 47680, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='owner_username',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
