# Generated by Django 2.2.5 on 2020-01-11 22:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0005_auto_20200111_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='post_Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 22, 19, 50, 938777, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 22, 19, 50, 939177, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='owner_username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL),
        ),
    ]
