# Generated by Django 2.2.5 on 2020-01-11 22:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0006_auto_20200111_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='post_Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 22, 21, 37, 749131, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 22, 21, 37, 749534, tzinfo=utc)),
        ),
    ]
