# Generated by Django 2.2.5 on 2020-01-16 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0007_auto_20200111_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='owner_email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 16, 14, 53, 6, 974354, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 16, 14, 53, 6, 975118, tzinfo=utc)),
        ),
    ]
